package main

// vocab_seed.go — regenerate the prose allow-list from cupel's curated catalogs.
//
// The vocabulary GATE has moved to calque (`calque vocab-check`, the substrate-
// general drift engine — see DESIGN_NOTES §16 there). What stays here is the
// cupel-specific part calque can't know: seeding the allow-list from cupel's own
// catalogs (engine names + cluster slugs + glossary slugs) merged with the manual
// theory/vocab-allowlist.txt. `vocab-seed` prints that merged set to stdout; the
// pre-commit hook writes it to .calque/vocab-allowlist.txt and runs the calque
// gate against it. (Was cmd/cupel/vocab_audit.go — the walk/tally/strict gate is
// now calque's; only the catalog auto-seed remains.)

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func runVocabSeed(args []string) {
	fs := flag.NewFlagSet("vocab-seed", flag.ContinueOnError)
	root := fs.String("dir", ".", "repo root")
	allowlistPath := fs.String("allowlist", "theory/vocab-allowlist.txt", "manual allow-list, merged in (one slug per line; # comments)")
	clusterCatalog := fs.String("clusters", "theory/cluster-catalog.md", "cluster catalog (for cluster slugs)")
	glossaryPath := fs.String("glossary", "theory/glossary.md", "glossary source (for glossary slugs)")
	if err := fs.Parse(args); err != nil {
		return
	}

	auto, autoErr := buildAutoAllowlist(*root, *clusterCatalog, *glossaryPath)
	if autoErr != nil {
		fmt.Fprintln(os.Stderr, "vocab-seed: warning:", autoErr)
	}
	explicit := loadExplicitAllowlist(filepath.Join(*root, *allowlistPath))
	merged := mergeAllowlists(auto, explicit)

	keys := make([]string, 0, len(merged))
	for k := range merged {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	fmt.Println("# calque vocab allow-list — generated by `cupel vocab-seed`.")
	fmt.Println("# Source: engine names + cluster slugs + glossary slugs + theory/vocab-allowlist.txt.")
	fmt.Println("# Regenerate after catalog changes; consumed by `calque vocab-check`.")
	fmt.Println()
	for _, k := range keys {
		fmt.Println(k)
	}
}

// buildAutoAllowlist seeds the allow-list from the engine list, the cluster
// catalog, and the glossary — cupel's already-curated vocabulary surfaces. Only
// hyphenated/slashed forms are admitted (the vocab gate only scans hyphenated
// compounds, so single-word entries can't match and would just bloat the seed).
func buildAutoAllowlist(root, clusterCatalog, glossaryPath string) (map[string]bool, error) {
	allow := map[string]bool{}
	add := func(s string) {
		if s == "" || !strings.ContainsAny(s, "-/") {
			return
		}
		if strings.Contains(s, " ") {
			return
		}
		allow[s] = true
	}

	sub, err := loadSubstrate()
	if err == nil {
		add("also-runs")
		for _, e := range sub.Engines {
			add(e.Name)
			add(e.Name + "-antagonist-mode")
			// Engine names with spaces ("virtue of defeat") appear in prose as
			// hyphenated forms ("virtue-of-defeat"); add those equivalents.
			if strings.Contains(e.Name, " ") {
				h := strings.ReplaceAll(e.Name, " ", "-")
				add(h)
				add(h + "-antagonist-mode")
			}
		}
	}

	clusters, cErr := loadClusters(filepath.Join(root, clusterCatalog))
	if cErr == nil {
		for _, c := range clusters {
			add(c.Slug)
		}
	}

	entries, gErr := loadGlossary(filepath.Join(root, glossaryPath))
	if gErr == nil {
		for _, e := range entries {
			add(e.Slug)
			for _, a := range e.Aliases {
				add(a)
			}
		}
	}

	var errs []string
	if err != nil {
		errs = append(errs, "engines: "+err.Error())
	}
	if cErr != nil {
		errs = append(errs, "clusters: "+cErr.Error())
	}
	if gErr != nil {
		errs = append(errs, "glossary: "+gErr.Error())
	}
	if len(errs) > 0 {
		return allow, fmt.Errorf("auto-allowlist partial: %s", strings.Join(errs, "; "))
	}
	return allow, nil
}

// loadExplicitAllowlist reads theory/vocab-allowlist.txt: one slug per line, #
// comments and blanks ignored.
func loadExplicitAllowlist(path string) map[string]bool {
	out := map[string]bool{}
	fh, err := os.Open(path)
	if err != nil {
		return out
	}
	defer fh.Close()
	sc := bufio.NewScanner(fh)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out[line] = true
	}
	return out
}

func mergeAllowlists(a, b map[string]bool) map[string]bool {
	out := map[string]bool{}
	for k := range a {
		out[k] = true
	}
	for k := range b {
		out[k] = true
	}
	return out
}
